# backend/app/services/report_builder.py

import os
from typing import Dict, Any, List

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib import colors


def _get_styles():
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="TitleLarge",
            parent=styles["Heading1"],
            fontSize=20,
            leading=24,
            spaceAfter=12,
        )
    )

    styles.add(
        ParagraphStyle(
            name="SectionHeading",
            parent=styles["Heading2"],
            fontSize=13,
            leading=16,
            spaceBefore=10,
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="Body",
            parent=styles["BodyText"],
            fontSize=10,
            leading=14,
            alignment=TA_LEFT,
            spaceAfter=6,
        )
    )

    styles.add(
        ParagraphStyle(
            name="Small",
            parent=styles["BodyText"],
            fontSize=8,
            leading=11,
            textColor=colors.grey,
        )
    )

    return styles


def _p(text: str, style: ParagraphStyle):
    """
    Helper: safe Paragraph creator.
    Keeps full sentences – no truncation.
    """
    if text is None:
        text = ""
    # Replace raw newlines with <br/> for reportlab
    text = str(text).replace("\n", "<br/>")
    return Paragraph(text, style)


def build_pdf_report(
    session_id: str,
    report: Dict[str, Any],
    output_path: str,
) -> str:
    """
    Build a detailed interview report PDF.

    Args:
        session_id: id of the interview session
        report: the same JSON structure you return from /api/report
        output_path: where to save the PDF

    Returns:
        The output_path (for convenience).
    """

    styles = _get_styles()
    story: List[Any] = []

    # -------- HEADER --------
    role = report.get("role", "Not specified")
    seniority = report.get("seniority", "Not specified")

    story.append(_p("Interview Performance Report", styles["TitleLarge"]))
    story.append(
        _p(
            f"Role: <b>{role}</b>   •   Level: <b>{seniority}</b>",
            styles["Body"],
        )
    )
    story.append(
        _p(
            f"Session ID: <font size='8'>{session_id}</font>",
            styles["Small"],
        )
    )
    story.append(Spacer(1, 12))

    # -------- OVERALL SCORES --------
    overall = report.get("overall") or {}

    story.append(_p("Overall Scores", styles["SectionHeading"]))

    score_data = [
      ["Content", _score_str(overall.get("content_score"))],
      ["Structure", _score_str(overall.get("structure_score"))],
      ["Clarity", _score_str(overall.get("clarity_score"))],
      ["Confidence", _score_str(overall.get("confidence_score"))],
    ]

    table = Table(score_data, colWidths=[120, 60])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2933")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 12))

    # -------- EXPRESSION SUMMARY --------
    emotion_summary = overall.get("emotion_summary") or {}
    dom_emotion = emotion_summary.get("dominant_emotion") or "Not enough data"

    story.append(_p("Expression Summary", styles["SectionHeading"]))
    story.append(
        _p(
            f"Dominant emotion detected across the interview: <b>{dom_emotion}</b>.",
            styles["Body"],
        )
    )
    story.append(Spacer(1, 12))

    # -------- STRENGTHS / IMPROVEMENTS / SUMMARY --------
    strengths = overall.get("strengths") or []
    improvements = overall.get("improvements") or []
    summary_text = overall.get("summary") or ""

    story.append(_p("Strengths", styles["SectionHeading"]))
    if strengths:
        for s in strengths:
            story.append(_p(f"• {s}", styles["Body"]))
    else:
        story.append(
            _p(
                "No specific strengths were generated by the AI for this session.",
                styles["Body"],
            )
        )
    story.append(Spacer(1, 8))

    story.append(_p("Areas to Improve", styles["SectionHeading"]))
    if improvements:
        for s in improvements:
            story.append(_p(f"• {s}", styles["Body"]))
    else:
        story.append(
            _p(
                "No specific improvements were generated. Try focusing on structure and using more concrete examples.",
                styles["Body"],
            )
        )
    story.append(Spacer(1, 8))

    if summary_text:
        story.append(_p("Overall Summary", styles["SectionHeading"]))
        story.append(_p(summary_text, styles["Body"]))
        story.append(Spacer(1, 12))

    # -------- PER-QUESTION BREAKDOWN --------
    questions = report.get("questions") or []

    if questions:
        story.append(_p("Question-wise Breakdown", styles["SectionHeading"]))
        story.append(Spacer(1, 4))

        for idx, q in enumerate(questions, start=1):
            q_text = q.get("question_text") or "Question text not available."
            transcript = q.get("transcript") or "Transcript not available."
            feedback = q.get("feedback") or "No detailed feedback for this question."

            story.append(_p(f"Question {idx}", styles["Body"]))
            story.append(_p(f"<b>{q_text}</b>", styles["Body"]))
            story.append(Spacer(1, 2))

            # Scores line
            q_scores = (
                f"Content: {_score_str(q.get('content_score'))}/10    "
                f"Structure: {_score_str(q.get('structure_score'))}/10    "
                f"Clarity: {_score_str(q.get('clarity_score'))}/10    "
                f"Confidence: {_score_str(q.get('confidence_score'))}/10"
            )
            story.append(_p(q_scores, styles["Small"]))

            # Transcript (full, wrapped, NOT truncated)
            story.append(_p(f"<b>Transcript:</b> {transcript}", styles["Body"]))

            # Feedback (full, wrapped)
            story.append(_p(f"<b>Feedback:</b> {feedback}", styles["Body"]))

            story.append(Spacer(1, 10))
    else:
        story.append(
            _p(
                "No per-question data is available for this session.",
                styles["Body"],
            )
        )

    # -------- BUILD DOCUMENT --------
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=40,
        rightMargin=40,
        topMargin=40,
        bottomMargin=40,
        title="Interview Report",
    )

    doc.build(story)
    return output_path


def _score_str(value):
  """Helper to format scores without truncating."""
  try:
      if value is None:
          return "–"
      return f"{float(value):.1f}"
  except Exception:
      return "–"
